-- V55 · Control económico privado
create table if not exists public.configuracion_economica_v55 (
  id smallint primary key default 1 check (id = 1),
  presupuesto_total numeric(12,2) not null default 0 check (presupuesto_total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
insert into public.configuracion_economica_v55 (id, presupuesto_total)
values (1,0) on conflict (id) do nothing;

create table if not exists public.gastos_boda_v55 (
  id bigint generated by default as identity primary key,
  fecha date not null default current_date,
  concepto text not null,
  categoria text not null default 'Otros',
  proveedor text,
  importe numeric(12,2) not null check (importe >= 0),
  pagado_por text not null default 'David' check (pagado_por in ('David','Raquel','Ambos','Personalizado')),
  porcentaje_david numeric(5,2) not null default 100 check (porcentaje_david between 0 and 100),
  forma_pago text not null default 'Transferencia',
  forma_pago_otro text,
  referencia text,
  estado text not null default 'pagado' check (estado in ('pagado','reserva','pendiente','cancelado')),
  fecha_vencimiento date,
  requiere_factura boolean not null default false,
  factura_recibida boolean not null default false,
  documento_url text,
  observaciones text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists gastos_boda_v55_fecha_idx on public.gastos_boda_v55(fecha desc);
create index if not exists gastos_boda_v55_estado_idx on public.gastos_boda_v55(estado);
create index if not exists gastos_boda_v55_categoria_idx on public.gastos_boda_v55(categoria);

alter table public.configuracion_economica_v55 enable row level security;
alter table public.gastos_boda_v55 enable row level security;

drop policy if exists "admin economia config" on public.configuracion_economica_v55;
create policy "admin economia config" on public.configuracion_economica_v55 for all to authenticated using (auth.email() = 'davidn6783@gmail.com') with check (auth.email() = 'davidn6783@gmail.com');
drop policy if exists "admin gastos boda" on public.gastos_boda_v55;
create policy "admin gastos boda" on public.gastos_boda_v55 for all to authenticated using (auth.email() = 'davidn6783@gmail.com') with check (auth.email() = 'davidn6783@gmail.com');

grant select, insert, update, delete on public.configuracion_economica_v55 to authenticated;
grant select, insert, update, delete on public.gastos_boda_v55 to authenticated;
grant usage, select on all sequences in schema public to authenticated;
