create table if not exists public.gastos_previstos_v55 (id bigint generated by default as identity primary key, concepto text not null, categoria text, importe_previsto numeric(12,2) not null default 0 check (importe_previsto >= 0), fecha_aproximada date, notas text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.gastos_previstos_v55 enable row level security;
drop policy if exists "gastos_previstos_admin_all" on public.gastos_previstos_v55;
create policy "gastos_previstos_admin_all" on public.gastos_previstos_v55 for all to authenticated using (true) with check (true);
