-- DAVID & RAQUEL · V23 ESTABILIZACIÓN
-- Ejecutar TODO este archivo en Supabase > SQL Editor > Run.

create extension if not exists pgcrypto;

-- =========================================================
-- 1. CONFIRMACIONES DE ASISTENCIA
-- =========================================================

create table if not exists public.invitados (
  id bigint generated by default as identity primary key,
  nombre text not null,
  telefono text,
  asistencia text not null,
  acompanante text,
  alergias text,
  comentarios text,
  created_at timestamptz not null default now()
);

-- Añade las columnas si la tabla ya existía con una estructura anterior.
alter table public.invitados add column if not exists telefono text;
alter table public.invitados add column if not exists acompanante text;
alter table public.invitados add column if not exists alergias text;
alter table public.invitados add column if not exists comentarios text;
alter table public.invitados add column if not exists created_at timestamptz not null default now();

alter table public.invitados enable row level security;
grant insert on table public.invitados to anon;
grant select on table public.invitados to authenticated;

drop policy if exists "permitir confirmaciones" on public.invitados;
create policy "permitir confirmaciones"
on public.invitados
for insert
to anon
with check (true);

drop policy if exists "solo novios pueden leer" on public.invitados;
create policy "solo novios pueden leer"
on public.invitados
for select
to authenticated
using (auth.uid() = '3c36865b-a156-476f-82fd-7d95a3aea21b'::uuid);

-- =========================================================
-- 2. ÁLBUM PRIVADO DE FOTOS Y VÍDEOS
-- =========================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'wedding-media',
  'wedding-media',
  false,
  104857600,
  array[
    'image/jpeg','image/png','image/webp','image/heic','image/heif',
    'video/mp4','video/quicktime'
  ]
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.media_uploads (
  id uuid primary key default gen_random_uuid(),
  object_path text unique not null,
  uploader_name text,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null default 0,
  created_at timestamptz not null default now()
);

alter table public.media_uploads enable row level security;
grant insert on table public.media_uploads to anon;
grant select, delete on table public.media_uploads to authenticated;

drop policy if exists "invitados registran sus archivos" on public.media_uploads;
create policy "invitados registran sus archivos"
on public.media_uploads
for insert
to anon
with check (true);

drop policy if exists "solo novios leen archivos" on public.media_uploads;
create policy "solo novios leen archivos"
on public.media_uploads
for select
to authenticated
using (auth.uid() = '3c36865b-a156-476f-82fd-7d95a3aea21b'::uuid);

drop policy if exists "solo novios borran registros de archivos" on public.media_uploads;
create policy "solo novios borran registros de archivos"
on public.media_uploads
for delete
to authenticated
using (auth.uid() = '3c36865b-a156-476f-82fd-7d95a3aea21b'::uuid);

-- Storage: invitados solo suben; no pueden listar ni descargar.
drop policy if exists "invitados suben recuerdos" on storage.objects;
create policy "invitados suben recuerdos"
on storage.objects
for insert
to anon
with check (
  bucket_id = 'wedding-media'
  and (storage.foldername(name))[1] = 'uploads'
);

-- Los novios pueden ver y descargar desde el panel privado.
drop policy if exists "solo novios ven recuerdos" on storage.objects;
create policy "solo novios ven recuerdos"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'wedding-media'
  and auth.uid() = '3c36865b-a156-476f-82fd-7d95a3aea21b'::uuid
);

drop policy if exists "solo novios borran recuerdos" on storage.objects;
create policy "solo novios borran recuerdos"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'wedding-media'
  and auth.uid() = '3c36865b-a156-476f-82fd-7d95a3aea21b'::uuid
);
